import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "./wagmi";
import { Providers } from "./providers";
import { JetBrains_Mono } from "next/font/google";
import Header from "../app/components/Header";
import React from "react";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

// 👇 Hacer async el RootLayout
export default async function RootLayout(props: { children: ReactNode }) {
  const cookieStore = await headers(); // 👈 ahora sí await
  const initialState = cookieToInitialState(getConfig(), cookieStore.get("cookie"));

  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} `}>
        <Providers initialState={initialState}>
          <Header />
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
